// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Gslc")>]
[<assembly: AssemblyProductAttribute("Gslc")>]
[<assembly: AssemblyDescriptionAttribute("GSL compiler command line application")>]
[<assembly: AssemblyVersionAttribute("0.1.1")>]
[<assembly: AssemblyFileVersionAttribute("0.1.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Gslc"
    let [<Literal>] AssemblyProduct = "Gslc"
    let [<Literal>] AssemblyDescription = "GSL compiler command line application"
    let [<Literal>] AssemblyVersion = "0.1.1"
    let [<Literal>] AssemblyFileVersion = "0.1.1"
