// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Gslc")>]
[<assembly: AssemblyProductAttribute("GSL")>]
[<assembly: AssemblyDescriptionAttribute("Compiler and tools for GSL.")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Gslc"
    let [<Literal>] AssemblyProduct = "GSL"
    let [<Literal>] AssemblyDescription = "Compiler and tools for GSL."
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
